// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ProductServiceGRPC.proto

package com.project.ecommerce.service;

public interface BooleanResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:net.devh.boot.grpc.example.BooleanResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool resp = 1;</code>
   */
  boolean getResp();
}
