// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ProductServiceGRPC.proto

package com.project.ecommerce.service;

public interface ProductOrBuilder extends
    // @@protoc_insertion_point(interface_extends:net.devh.boot.grpc.example.Product)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 id = 1;</code>
   */
  long getId();

  /**
   * <code>string title = 2;</code>
   */
  String getTitle();
  /**
   * <code>string title = 2;</code>
   */
  com.google.protobuf.ByteString
      getTitleBytes();

  /**
   * <code>string description = 3;</code>
   */
  String getDescription();
  /**
   * <code>string description = 3;</code>
   */
  com.google.protobuf.ByteString
      getDescriptionBytes();

  /**
   * <code>double price = 4;</code>
   */
  double getPrice();

  /**
   * <code>string category = 5;</code>
   */
  String getCategory();
  /**
   * <code>string category = 5;</code>
   */
  com.google.protobuf.ByteString
      getCategoryBytes();

  /**
   * <code>string addedOn = 6;</code>
   */
  String getAddedOn();
  /**
   * <code>string addedOn = 6;</code>
   */
  com.google.protobuf.ByteString
      getAddedOnBytes();
}
